export const SET_USERTOKEN = 'SET_USERTOKEN';
export const SET_USERINFO = 'SET_USERINFO';
export const SET_USERS = 'SET_USERS';
export const SET_SELECTEDUSERS = 'SET_SELECTEDUSERS';
export const SET_GROUPS = 'SET_GROUPS';
